export const OPEN_POPUP_LOGIN = 'OPEN_POPUP_LOGIN';
export const SET_USER_AUTH = 'SET_USER_AUTH';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_SHOW_POPUP_ADD_ROOM = 'SET_IS_SHOW_POPUP_ADD_ROOM';
export const SET_NAME_FORM_ROOM = 'SET_NAME_FORM_ROOM';
export const SET_DESCRIPTION_ROOM = 'SET_DESCRIPTION_ROOM';
export const SET_USER_SELECTION_FORM_ROOM = 'SET_USER_SELECTION_FORM_ROOM';
export const SUBMIT_FORM_ADD_ROOM = 'SUBMIT_FORM_ADD_ROOM';
export const SET_IS_ROOM_FORM_LOADING = 'SET_IS_ROOM_FORM_LOADING';
export const SET_CURRENT_ROOMS = 'SET_CURRENT_ROOMS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
// Chat
export const SET_CHAT_CURRENT_ROOM = 'SET_CHAT_CURRENT_ROOM';
export const SET_USERS_IN_CURRENT_ROOM = 'SET_USERS_IN_CURRENT_ROOM';
export const SET_IS_SHOW_POPUP_ADD_INVITE = 'SET_IS_SHOW_POPUP_ADD_INVITE';
export const SET_MESSAGE_SEND = 'SET_MESSAGE_SEND';
export const SUBMIT_SEND_MESSAGE = 'SUBMIT_SEND_MESSAGE';
export const SET_MESSAGE_IN_CURRENT_ROOM = 'SET_MESSAGE_IN_CURRENT_ROOM';
// User
export const SET_USERS = 'SET_USERS';
export const SET_USER_SELECTION_FORM_INVITE = 'SET_USER_SELECTION_FORM_INVITE';
export const SET_IS_INVITE_FORM_LOADING = 'SET_IS_INVITE_FORM_LOADING';
export const SUBMIT_FORM_INVITE_USERS = 'SUBMIT_FORM_INVITE_USERS';
export const DELETE_USER_IN_ROOM = 'DELETE_USER_IN_ROOM';